// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Threading;
using NUnit.Framework;

namespace BareBonesWS
{
	[TestFixture()]
	public class WebSocketTest
	{
		[Test()]
		public void CanParseURL()
		{
			WebSocket ws = new WebSocket("ws://chain-api.media.mit.edu/ws/site-5");
			Assert.AreEqual(ws.Host, "chain-api.media.mit.edu");
			Assert.AreEqual(ws.Path, "/ws/site-5");
			ws.Close();
		}
		[Test()]
		public void MessagesReceived()
		{
			WebSocket ws = new WebSocket("ws://chain-api.media.mit.edu/ws/site-5");
			Console.WriteLine(ws.ReadMessage());
			Console.WriteLine(ws.ReadMessage());
			ws.Close();
		}
		[Test()]
		public void ListenerCallsCallback()
		{
			WebSocket ws = new WebSocket("ws://chain-api.media.mit.edu/ws/site-5");
			ws.OnMessage += MsgReceived;
			ws.SpawnListener();
			Thread.Sleep(2000);
			ws.Close();
		}

		void MsgReceived(string msg) {
			Console.WriteLine(msg);
		}

	}
}

